version: '3.7'

services: 
    postgres:
        user: root
        image: postgres:12
        volumes:
            - db:/var/lib/postgresql/data
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            my-net:
                ipv4_address: 10.6.0.100
        ports: 
            - "5434:5432"

    bond:
        image: james-bond
        #secrets:
        #    - id_rsa
        build:
            context: .
            args:
                - DISCORD_KEY=${DISCORD_KEY}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                - POSTGRES_HOST=10.6.0.100
                - POSTGRES_PORT=5432
        depends_on: 
            - postgres
        networks:
            - my-net
        volumes: 
            - logs:/root/docker/bond/logs

volumes:
    db:
    logs:

networks:
    my-net:
        driver: bridge
        ipam:
         config:
            - subnet: 10.6.0.0/16
#secrets:
#    id_rsa:
#        file: ./id_rsa